### ISSUE TITLE
[BACK] Melhorias back

### ISSUE THREAD

**Issue by JoaoM-py** [The-Bugger-Ducks/help-duck-tickets#25]
[CHAMADOS] :
- [x] Listar por prioridade e data de criação;

```
@GetMapping
public Page<Tipagem> listagem( 
    @RequestParam(required = false) String nomeCurso, 
    @PageableDefault(sort = "id", direction = Direction.DESC) Pageable paginacao) {
}
```

---
#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [ ] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by MariaGabrielaReis** [comment]
<h1 align="center"> Documentação 📄 </h1>

### Tecnologias utilizadas:
As seguintes tecnologias foram utilizadas para o desenvolvimento dessa tarefa: Java/Spring, Visual Studio Code.

### Ordenação por prioridade e data de criação:
| Antes  | Depois  |
| :------: | :--------: |
| ![image](https://user-images.githubusercontent.com/69374340/169593539-632b645e-5158-44dc-aafa-2e49d7235ae7.png) |  em breve... |
